package org.eoisaac.views;

import javax.swing.*;

/**
 * @author saulo.cabral
 */
public class AppFrame extends javax.swing.JFrame {
  private javax.swing.JButton deletarBtn;
  private javax.swing.JLabel diferencaTxt;
  private javax.swing.JTable entradasTabela;

  private javax.swing.JRadioButton gastoBtn;
  private javax.swing.JLabel gastoTxt;

  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel9;
  private javax.swing.JPanel jPanel1;
  private javax.swing.JScrollPane jScrollPane1;

  private javax.swing.JLabel recebidoTxt;

  public AppFrame() {
    initComponents();
  }

    public static void main(String args[]) {
      try {
        for (javax.swing.UIManager.LookAndFeelInfo info :
            javax.swing.UIManager.getInstalledLookAndFeels()) {
          if ("Nimbus".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
          }
        }
      } catch (ClassNotFoundException
          | InstantiationException
          | IllegalAccessException
          | UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(AppFrame.class.getName())
            .log(java.util.logging.Level.SEVERE, null, ex);
      }

      java.awt.EventQueue.invokeLater(
          new Runnable() {
            public void run() {
              new AppFrame().setVisible(true);
            }
          });
    }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT
   * modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated
  // Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    TransactionFormView transactionFormView = new TransactionFormView();
    transactionFormView.render();

    jPanel1 = new javax.swing.JPanel();
    gastoBtn = new javax.swing.JRadioButton();

    jScrollPane1 = new javax.swing.JScrollPane();
    entradasTabela = new javax.swing.JTable();
    deletarBtn = new javax.swing.JButton();
    jLabel5 = new javax.swing.JLabel();
    recebidoTxt = new javax.swing.JLabel();
    jLabel7 = new javax.swing.JLabel();
    gastoTxt = new javax.swing.JLabel();
    jLabel9 = new javax.swing.JLabel();
    diferencaTxt = new javax.swing.JLabel();
    jLabel6 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jPanel1.setBackground(new java.awt.Color(255, 255, 255));

    entradasTabela.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    entradasTabela.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    entradasTabela.setModel(
        new javax.swing.table.DefaultTableModel(
            new Object[][] {
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null},
              {null, null, null, null}
            },
            new String[] {"Title 1", "Title 2", "Title 3", "Title 4"}));
    jScrollPane1.setViewportView(entradasTabela);

    deletarBtn.setText("DEL");

    jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel5.setText("Recebido (R$):");

    recebidoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    recebidoTxt.setText("0.00");

    jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel7.setText("Gastos (R$):");

    gastoTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    gastoTxt.setText("0.00");

    jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    jLabel9.setText("Diferença (R$):");

    diferencaTxt.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
    diferencaTxt.setText("0.00");

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
    jLabel6.setText("Finanças Anual Seu José");

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                jPanel1Layout
                    .createSequentialGroup()
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(
                                        transactionFormView,
                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(
                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(
                                        jPanel1Layout
                                            .createParallelGroup(
                                                javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(
                                                jPanel1Layout
                                                    .createSequentialGroup()
                                                    .addComponent(jLabel5)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(recebidoTxt)
                                                    .addGap(75, 75, 75)
                                                    .addComponent(jLabel7)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(gastoTxt)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        Short.MAX_VALUE)
                                                    .addComponent(jLabel9)
                                                    .addPreferredGap(
                                                        javax.swing.LayoutStyle.ComponentPlacement
                                                            .RELATED)
                                                    .addComponent(diferencaTxt)
                                                    .addGap(47, 47, 47)
                                                    .addComponent(deletarBtn))
                                            .addComponent(
                                                jScrollPane1,
                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                592,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(
                                jPanel1Layout
                                    .createSequentialGroup()
                                    .addGap(363, 363, 363)
                                    .addComponent(jLabel6)))
                    .addContainerGap(16, Short.MAX_VALUE)));
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(
                javax.swing.GroupLayout.Alignment.TRAILING,
                jPanel1Layout
                    .createSequentialGroup()
                    .addComponent(jLabel6)
                    .addPreferredGap(
                        javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(
                                transactionFormView,
                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(
                        jPanel1Layout
                            .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deletarBtn)
                            .addComponent(jLabel5)
                            .addComponent(recebidoTxt)
                            .addComponent(jLabel7)
                            .addComponent(gastoTxt)
                            .addComponent(jLabel9)
                            .addComponent(diferencaTxt))
                    .addContainerGap()));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    layout.setVerticalGroup(
        layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(
                jPanel1,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                javax.swing.GroupLayout.DEFAULT_SIZE,
                Short.MAX_VALUE));
    pack();
  } // </editor-fold>//GEN-END:initComponents

  private void ganhoBtnActionPerformed(
      java.awt.event.ActionEvent evt) { // GEN-FIRST:event_ganhoBtnActionPerformed
    // TODO add your handling code here:
  } // GEN-LAST:event_ganhoBtnActionPerformed
}
